### PR TITLE
Fix post-B.1.1.7 batch

### PR DESCRIPTION
**Pull request by wm75**
Previous links were incomplete.

### CODE REVIEW

**Comment by simonbray** [comment]
I guess you realise, but this will create two separate uploads.

**Comment by wm75** [comment]
@simonbray that's what I was expecting so I deleted the first, partial one in Galaxy. However, it didn't upload anything the second time. Maybe cause I didn't create a new file?

**Comment by simonbray** [comment]
Yes it did not upload: https://github.com/usegalaxy-eu/sars-cov-2-processing-requests/runs/2427668767#step:3:13

That was not what I was expecting, but on reflection I think it's good, it seems cleaner always to create a new file.

**Comment by wm75** [comment]
Agreed 👍

**Pull request merged**
